services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_availability
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d team_availability"]
      interval: 3s
      timeout: 3s
      retries: 15
    # no ports/volumes -> ephemeral db that dies with the stack

  init-db:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/team_availability
    command: >
      sh -c "python -m server.scripts.create_db"
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/team_availability
    depends_on:
      db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
    command: >
      uvicorn server.main:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers
      --forwarded-allow-ips="*"
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:80"
    restart: unless-stopped
